# -*- coding: utf-8 -*-
"""model_io.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2mipyeYkM8RFkw2fa5G536OdhauQ08C
"""

import pandas as pd
import numpy as np
import joblib
import warnings
warnings.filterwarnings('ignore')

def Load_model():
        input1 = float(input("Enter Car Year in range 2000-2005: "))
        input2 = float(input("Enter Euro standard in range 2-4: "))
        input3 = float(input("Enter Engine Capacity in range 800-7000: "))
        input4 = float(input("Enter CO2 emission value in range 100-500: "))
        input5 = float(input("Enter Combined metrics in range 4.0-10.0: "))
        input6 = float(input("Enter combined imperial in range 20.0-80.0: "))
        input7 = float(input("Enter 1 if fuel type is Diesel else 0: "))
        input8 = float(input("Enter 1 if fuel type is LpG else 0: "))
        input9 = float(input("Enter 1 if fuel type is Petrol else 0: "))

        inputs = np.array([input1, input2, input3, input4, input5, input6, input7, input8, input9,])
        Loaded_model=joblib.load('/content/drive/MyDrive/ML Models/fuel_cost_6000_miles.sav')
        prediction = Loaded_model.predict([inputs])
        return print("Fuel cost for 6000 miles is: £",prediction[0])
Load_model()